package servlets;

import dao.VehicleDAO;
import models.Vehicle;
import java.io.IOException;
import java.sql.SQLException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/addVehicle")
public class AddVehicleServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.getRequestDispatcher("add-vehicle.jsp").forward(request, response); // Display a form for adding a new vehicle
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String plateNumber = request.getParameter("plateNumber");
        String vehicleType = request.getParameter("vehicleType");

        Vehicle vehicle = new Vehicle(0, plateNumber, vehicleType); // vehicleId will be auto-generated by DB
        VehicleDAO vehicleDAO = new VehicleDAO();
        try {
            if (vehicleDAO.addVehicle(vehicle)) {
                response.sendRedirect("getAllVehicles"); // Redirect to the page showing all vehicles
            } else {
                response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Error adding vehicle");
            }
        } catch (SQLException e) {
            response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Error adding vehicle");
        }
    }
}
